# Generated by Django 4.1.2 on 2022-12-12 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=4)),
                ('date1', models.DateTimeField(help_text='Enter the value in DD/MM/YY HH:MM')),
                ('date2', models.DateTimeField(help_text='Enter the value in DD/MM/YY HH:MM')),
                ('temp1', models.FloatField(help_text='Enter the Minimum Temperature Recorded')),
                ('temp2', models.FloatField(help_text='Enter the Maximum Temperature Recorded')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
