# Generated by Django 4.1.2 on 2022-12-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='number',
            field=models.IntegerField(),
        ),
    ]
