# Generated by Django 4.1.2 on 2022-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_sensordata_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='interval',
            field=models.IntegerField(default=15),
        ),
    ]
